# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 337)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 70, 71, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 70, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 71, 31))
        self.label_2.setObjectName("label_2")
        self.lineEditSurname = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditSurname.setGeometry(QtCore.QRect(120, 120, 141, 22))
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.checkBoxPrivate = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBoxPrivate.setGeometry(QtCore.QRect(50, 170, 131, 20))
        self.checkBoxPrivate.setChecked(True)
        self.checkBoxPrivate.setObjectName("checkBoxPrivate")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 220, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.result = QtWidgets.QLabel(parent=Dialog)
        self.result.setGeometry(QtCore.QRect(0, 270, 581, 51))
        self.result.setText("")
        self.result.setObjectName("result")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(290, 60, 121, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Internista = QtWidgets.QRadioButton(parent=self.widget)
        self.Internista.setChecked(True)
        self.Internista.setObjectName("Internista")
        self.verticalLayout.addWidget(self.Internista)
        self.Pediatra = QtWidgets.QRadioButton(parent=self.widget)
        self.Pediatra.setObjectName("Pediatra")
        self.verticalLayout.addWidget(self.Pediatra)
        self.Dermatolog = QtWidgets.QRadioButton(parent=self.widget)
        self.Dermatolog.setObjectName("Dermatolog")
        self.verticalLayout.addWidget(self.Dermatolog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie:"))
        self.label_2.setText(_translate("Dialog", "Nazwisko:"))
        self.checkBoxPrivate.setText(_translate("Dialog", "Wizyta prywatna"))
        self.pushButton.setText(_translate("Dialog", "Rezerwuj"))
        self.label_3.setText(_translate("Dialog", "Lekarz: "))
        self.Internista.setText(_translate("Dialog", "Internista"))
        self.Pediatra.setText(_translate("Dialog", "Pediatra"))
        self.Dermatolog.setText(_translate("Dialog", "Dermatolog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
